name: Build-and-Test
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
 build:
  runs-on: ubuntu-latest
  env:
    configuration: release
    test_var: test_v1
  steps:
  # checkout all sources from git
  - name: Checkout Sources
    uses: actions/checkout@v4
  - name: echo test
    run: echo "echo test is working" ${{ env.test_var }}
  # install dotnet SDK
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 8.0.x
  # restore NuGet packages
  - name: Restore dependencies
    run: dotnet restore
  # build the project
  - name: Build
    run: dotnet build --no-restore  --configuration ${{ env.configuration }}
  - name: Test
    run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}

  
